[build]
  base = "frontend"
  publish = "build"
  command = "npm install --no-audit --no-fund $NPM_FLAGS && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
